# basic options
title: Veterans Safaris 
author: Mutembo Senyana Kavos
email: your-email@domain.com
description: The best travel site in Musanze 
twitter_username: veteranstours
github_username:  

plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
theme: minima
