# basic options
title: Veterans Safaris 
author: Mutembo Senyana Kavos

email: veteranstours@gmail.com
description: The best travel site in Musanze 
github_username: veteranssafaris
twitter_username: veteranstours
facebook_username: hikenyiragongovolcano
linkedin_username: 
instagram_username: veteranstours
google_plus_username: googleplus


baseurl: /veteranssafaris

plugins:
  - jekyll-feed
  - jekyll-maps

# Build settings
markdown: kramdown
theme: minima

# If you want to link only specific pages in your header, uncomment 
# this and add the path to the pages in order as they should show up 
# header_pages: 
# - about.html 
header_pages:
- about.md
- tourprograms.md
- car_hire.md
- generalterms.md
- Markdown_Examples.md


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      comments: true
