# basic options
title: Veterans Safaris 
author: Mutembo Senyana Kavos

email: your-email@domain.com
description: The best travel site in Musanze 
twitter_username: veteranstours
github_username:  

plugins:
  - jekyll-feed
  - jekyll-maps
# Build settings
markdown: kramdown
theme: minima

# If you want to link only specific pages in your header, uncomment 
# this and add the path to the pages in order as they should show up 
# header_pages: 
# - about.html 
header_pages:
- about.md
- tourprogramsrwanda.md
- trips.md
- generalterms.md